import { LanguageConfig } from './types';

export const gujaratiConfig: LanguageConfig = {
  vowels: "(A((o)|(O))?)|(a((A)|(a)|(u)|(i))?)|(En)|(e(e)?)|(I)|(H)|(TR)|(M)|(o(o)?)|(tR)|(i)|(U)|(u)|([:])|([|]([|])?)|(Om)",
  consonants: "(Ch)|(D(dD|h)?)|(G)|(L(lL)?)|(N(nN)?)|(R(rRU)?)|(Sh)|(Th?)|(Y)|(bh?)|(ch)|(dh?)|(f)|(g(h|G)?)|(h)|(jh?)|(kh?)|(l)|(m)|(nY?)|(ph?)|(qh?)|(r)|(sh?)|(th?)|(v)|(y)|(z)|(Bh?)",
  letterCodes: {
    "~a": "\u0A85",
    "~aa": "\u0A86", "~A": "\u0A86",
    "~i": "\u0A87",
    "~ee": "\u0A88", "~I": "\u0A88",
    "~u": "\u0A89",
    "~oo": "\u0A8A", "~U": "\u0A8A",
    "~tR": "\u0A8B",
    "~En": "\u0A8D",
    "~e": "\u0A8F",
    "~ai": "\u0A90",
    "~Ao": "\u0A91",
    "~o": "\u0A93",
    "~au": "\u0A94",
    "~AO": "\u0A81",
    "~Om": "\u0AD0",
    "~M": "\u0A82",
    "~H": "\u0A83",
    "~:": "\u0A83",

    "AO": "\u0A81",
    "H": "\u0A83",
    ":": "\u0A83",
    "Ao": "\u0A91",
    "M": "\u0A82",

    "a": "",
    "aa": "\u0ABE", "A": "\u0ABE",
    "i": "\u0ABF",
    "e": "\u0AC7",
    "ee": "\u0AC0", "I": "\u0AC0",
    "u": "\u0AC1",
    "oo": "\u0AC2", "U": "\u0AC2",
    "ai": "\u0AC8",
    "o": "\u0ACB",
    "au": "\u0ACC",
    "*": "\u0ACD",
    "tR": "\u0AC3",
    "TR": "\u0AC4",

    "k": "\u0A95",
    "kh": "\u0A96",
    "g": "\u0A97",
    "gh": "\u0A98",
    "G": "\u0A99",
    "ch": "\u0A9A",
    "Ch": "\u0A9B",
    "chh": "\u0A9B",
    "j": "\u0A9C",
    "jh": "\u0A9D",
    "nY": "\u0A9E",
    "t": "\u0A9F",
    "T": "\u0AA0",
    "d": "\u0AA1",
    "D": "\u0AA2",
    "N": "\u0AA3",
    "th": "\u0AA4",
    "Th": "\u0AA5",
    "dh": "\u0AA6",
    "Dh": "\u0AA7",
    "n": "\u0AA8",
    "p": "\u0AAA",
    "ph": "\u0AAB",
    "b": "\u0AAC",
    "bh": "\u0AAD", "B": "\u0AAD", "Bh": "\u0AAD",
    "m": "\u0AAE",
    "y": "\u0AAF",
    "r": "\u0AB0",
    "l": "\u0AB2",
    "v": "\u0AB5",
    "sh": "\u0AB6",
    "Sh": "\u0AB7",
    "s": "\u0AB8",
    "h": "\u0AB9",
    "LlL": "\u0AB3",
    "q": "\u0A95",
    "qh": "\u0A96",
    "gG": "\u0A97",
    "z": "\u0A9C",
    "DdD": "\u0AA1",
    "RrR": "\u0AB0",
    "f": "\u0AAB",
    "Y": "\u0AAF"
  }
};
