import { LanguageConfig } from './types';

export const kannadaConfig: LanguageConfig = {
  vowels: "(A)|(a((a)|(i)|(e)|(u))?)|(E)|(o((a)|(o))?)|(I)|(H)|(M)|(O)|(i)|(U)|(TR)|(e(e)?)|(u)|(tR)",
  consonants: "(Ch)|(B(h)?)|(D(h)?)|(K(h)?)|(J(h)?)|(L)|(N)|(Sh)|(T(h)?)|(ch)|(b(h)?)|(d(h)?)|(g(h)?)|(f)|(h)|(k(h)?)|(j(h)?)|(m)|(l)|(n((Y)|(G))?)|(p(h)?)|(s(h)?)|(r(R)?)|(t(h)?)|(v)|(w)|(y)",
  letterCodes: {
    "~a": "\u0C85",
    "~aa": "\u0C86",
    "~A": "\u0C86",
    "~i": "\u0C87",
    "~ee": "\u0C88",
    "~I": "\u0C88",
    "~u": "\u0C89",
    "~oo": "\u0C8A",
    "~U": "\u0C8A",
    "~e": "\u0C8E",
    "~ae": "\u0C8F",
    "~E": "\u0C8F",
    "~ai": "\u0C90",
    "~o": "\u0C92",
    "~oa": "\u0C93",
    "~O": "\u0C93",
    "~au": "\u0C94",
    "~tR": "\u0C8B",
    "~TR": "\u0CD8",
    "~M": "\u0C82",
    "~H": "\u0C83",

    "a": "",
    "*": "\u0CCD",
    "aa": "\u0CBE",
    "A": "\u0CBE",
    "i": "\u0CBF",
    "ee": "\u0CC0",
    "I": "\u0CC0",
    "u": "\u0CC1",
    "oo": "\u0CC2",
    "U": "\u0CC2",
    "e": "\u0CC6",
    "ae": "\u0CC7",
    "E": "\u0CC7",
    "ai": "\u0CC8",
    "o": "\u0CCA",
    "oa": "\u0CCB",
    "O": "\u0CCB",
    "au": "\u0CCC",
    "tR": "\u0CC3",
    "TR": "\u0CC4",
    "M": "\u0C82",
    "H": "\u0C83",

    "k": "\u0C95", "K": "\u0C95",
    "kh": "\u0C96", "Kh": "\u0C96",
    "g": "\u0C97",
    "gh": "\u0C98",
    "nG": "\u0C99",
    "ch": "\u0C9A",
    "Ch": "\u0C9B",
    "j": "\u0C9C",
    "jh": "\u0C9D", "J": "\u0C9D", "Jh": "\u0C9D",
    "nY": "\u0C9E",
    "t": "\u0C9F",
    "T": "\u0CA0",
    "d": "\u0CA1",
    "D": "\u0CA7",
    "N": "\u0CA3",
    "th": "\u0CA4",
    "Th": "\u0CA5",
    "dh": "\u0CA6",
    "Dh": "\u0CA7",
    "n": "\u0CA8",
    "p": "\u0CAA",
    "ph": "\u0CAB",
    "b": "\u0CAC",
    "bh": "\u0CAD", "B": "\u0CAD", "Bh": "\u0CAD",
    "m": "\u0CAE",
    "y": "\u0CAF",
    "r": "\u0CB0",
    "rR": "\u0CB1",
    "R": "\u0CB1",
    "l": "\u0CB2",
    "L": "\u0CB3",
    "v": "\u0CB5", "w": "\u0CB5",
    "sh": "\u0CB6",
    "Sh": "\u0CB7",
    "s": "\u0CB8",
    "h": "\u0CB9",
    "f": "\u0CAB"
  }
};
