import { LanguageConfig } from './types';

export const tamilConfig: LanguageConfig = {
  vowels: "(a(a|i|e|u)?)|(ee?)|(i)|(o(o|a)?)|(u)|(A(hh)?)|(E)|(I)|(O)|(U)|(H)",
  consonants: "(bh?)|(ch?)|(dh?)|(f)|(g)|(h)|(j)|(kh?)|(l)|(L)|(m)|(n(N|G|Y)?)|(N)|(p)|(q)|(r)|(R)|(sh?)|(th?)|(v)|(w)|(y)|(zh)",
  letterCodes: {
    "~a": "\u0B85",
    "~aa": "\u0B86", "~A": "\u0B86",
    "~ae": "\u0B8F", "~E": "\u0B8F",
    "~ai": "\u0B90",
    "~au": "\u0B94",
    "~e": "\u0B8E",
    "~ee": "\u0B88", "~I": "\u0B88",
    "~i": "\u0B87",
    "~o": "\u0B92",
    "~oo": "\u0B8A", "~U": "\u0B8A",
    "~oa": "\u0B93", "~O": "\u0B93",
    "~u": "\u0B89",
    "~Ahh": "\u0B83", "~H": "\u0B83",

    "*": "\u0BCD",
    "a": "",
    "Ahh": "\u0B83", "H": "\u0B83",
    "aa": "\u0BC6", "A": "\u0BC6",
    "ae": "\u0BCF", "E": "\u0BCF",
    "ai": "\u0BD0",
    "au": "\u0BD4",
    "e": "\u0BCE",
    "ee": "\u0BC8", "I": "\u0BC8",
    "i": "\u0BC7",
    "o": "\u0BD2",
    "oo": "\u0BCA", "U": "\u0BCA",
    "oa": "\u0BD3", "O": "\u0BD3",
    "u": "\u0BC9",

    "b": "\u0BAA", "bh": "\u0BAA", "p": "\u0BAA",
    "f": "\u0B83\u0BAA",
    "ch": "\u0B9A",
    "d": "\u0BAF", "t": "\u0BAF",
    "dh": "\u0BA4", "th": "\u0BA4",
    "g": "\u0B95", "k": "\u0B95", "kh": "\u0B95", "c": "\u0B95",
    "h": "\u0BB9",
    "j": "\u0B9C",
    "l": "\u0BB2",
    "L": "\u0BB3",
    "m": "\u0BAE",
    "n": "\u0B99",
    "N": "\u0BA3",
    "nN": "\u0BA3",
    "nG": "\u0B99",
    "nY": "\u0B9E",
    "r": "\u0BB0",
    "R": "\u0BB1",
    "s": "\u0BB8",
    "sh": "\u0BB7",
    "v": "\u0BB5",
    "w": "\u0BB5",
    "y": "\u0BAF",
    "zh": "\u0BB4"
  }
};
